import { useRouter } from "next/router";
import Head from "next/head";
import { useEffect, useState } from "react";
import Link from "next/link";

const ProductDetail = () => {
  const [product, setProduct] = useState(null);
  const router = useRouter();
  const { productId } = router.query;

  useEffect(() => {
    const getProduct = async () => {
      try {
        const response = await fetch(`/api/products/${productId}`);
        if (response.ok) {
          const data = await response.json();
          setProduct(data);
        } else {
          throw new Error(`Fetch failed with status code ${response.status}`);
        }
      } catch (error) {
        alert(error);
      }
    };
    if (productId) {
      getProduct();
    }
  }, [productId]);

  return (
    <>
      <Head>
        <title>Produkt Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {product ? (
        <>
          <p>Name: {product.name}</p>
          <p>Category: {product.category}</p>
          <p>Details: {product.detail}</p>
        </>
      ) : (
        <p>Loading...</p>
        //Ladebalken
      )}
      <Link href="/products">Back</Link>
    </>
  );
};

export default ProductDetail;
