import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import styled from "styled-components";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MyHeading>Ich bin live!!</MyHeading>

      <div>
        <Link href="/products">Zu den Produkten per Link</Link>
      </div>
    </div>
  );
}

const MyHeading = styled.h1`
  color: green;
`;
